version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: python:3.10
    steps:
      - checkout

      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install Dependencies
          command: |
            uv pip install --system -r requirements.txt
            uv pip install --system -e .

      - run:
          name: Ensure Log File Exists
          command: |
            mkdir -p src/logger
            touch src/logger/operations.log
            ls -l src/logger/operations.log  # ✅ Print file details to confirm creation

      - run:
          name: Set PYTHONPATH
          command: |
            echo "export PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $BASH_ENV
            source $BASH_ENV
            echo "PYTHONPATH is set to: $PYTHONPATH"  # ✅ Verify PYTHONPATH is set correctly

      - run:
          name: Run Ruff Linting
          command: |
            ruff check src/ tests/ || true

      - run:
          name: Run Mypy Type Checking
          command: |
            mypy src/ || true

      - run:
          name: Verify Tests Exist
          command: pytest --collect-only tests/ src/ # ✅ Ensure tests are collected from both `tests/` and `src/`

      - run:
          name: Run Tests with Coverage
          command: |
            pytest tests/ src/ --cov=src --cov-report=xml --cov-report=html --junitxml=test-results/junit.xml \
            --cov-config=pyproject.toml | tee test-results/output.log  # ✅ Ensure `test_logger.py` is executed

      - run:
          name: Check Test Results
          command: |
            if grep -q 'FAILED' test-results/output.log; then
              echo "Some tests failed. Check logs."
            else
              echo "All tests passed!"
            fi

      - store_test_results:
          path: test-results/

      - store_artifacts:
          path: htmlcov/
          destination: coverage_html

      - store_artifacts:
          path: test-results/output.log

workflows:
  version: 2
  test-workflow:
    jobs:
      - lint_and_test
