version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install uv
            uv pip install -r requirements.txt
      - run:
          name: Run Ruff Linting
          command: ruff check src/ tests/
      - run:
          name: Run Mypy Type Checking
          command: mypy src/
      - run:
          name: Run Tests with Coverage
          command: |
            pytest --cov=src --cov-report=xml --cov-report=html --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: htmlcov/

workflows:
  version: 2
  validate:
    jobs:
      - lint_and_test
